service: line-weather-bot

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
  environment:
    LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
    LINE_CHANNEL_TOKEN: ${env:LINE_CHANNEL_TOKEN}

functions:
  input:
    handler: handler.input
    events:
      - http:
          path: weather-bot/input
          method: post

package:
  include:
    - handler.rb         

plugins:
  - serverless-ruby-package