service: line-weather-bot

custom:
  bucket: line-weather-bot-user-information

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
  environment:
    LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
    LINE_CHANNEL_TOKEN: ${env:LINE_CHANNEL_TOKEN}
    LIVEDOOR_PRIMARY_AREA_RSS: http://weather.livedoor.com/forecast/rss/primary_area.xml
    USER_INFO_BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  input:
    handler: handler.input
    events:
      - http:
          path: weather-bot/input
          method: post

resources:
  Resources:
    userInformationBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

package:
  include:
    - handler.rb         

plugins:
  - serverless-ruby-package