service: line-weather-bot

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  memorySize: 128
  timeout: 30

functions:
  input:
    handler: handler.input
    events:
      - http:
          path: weather-bot/input
          method: post